#!/bin/bash

# Simple script to add A record for npi.aimpactnexus.ai
echo "🚀 Adding A record for npi.aimpactnexus.ai..."
echo ""
echo "Since we don't have GoDaddy API credentials, please add this manually:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 MANUAL DNS CONFIGURATION REQUIRED:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Go to GoDaddy DNS Management:"
echo "   https://dcc.godaddy.com/control/aimpactnexus.ai/dns"
echo ""
echo "2. Add the following A record:"
echo "   Type: A"
echo "   Name: npi"
echo "   Value: 76.76.21.21"
echo "   TTL: 600 seconds (10 minutes)"
echo ""
echo "3. Click 'Save' to apply changes"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Once added, your site will be available at:"
echo "   https://npi.aimpactnexus.ai"
echo ""
echo "⏱️  DNS propagation may take 5-30 minutes"
echo "🔒 SSL certificate will be automatically provisioned by Vercel"
echo ""
echo "💡 Check propagation status with:"
echo "   nslookup npi.aimpactnexus.ai"
echo "   dig npi.aimpactnexus.ai"
echo ""