import { NextRequest, NextResponse } from 'next/server'

export async function GET(req: NextRequest) {
  try {
    // For now, we'll return a pre-created PDF or create a simple one
    // This is a placeholder response that redirects to a sample PDF
    
    const samplePdfContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Nexus Precision Industries - AI Manufacturing Intelligence Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
          .header { text-align: center; margin-bottom: 30px; }
          .logo { color: #0891b2; font-size: 24px; font-weight: bold; }
          .title { color: #1f2937; font-size: 20px; margin: 10px 0; }
          .subtitle { color: #6b7280; font-size: 14px; }
          .section { margin: 20px 0; }
          .metric { background: #f3f4f6; padding: 15px; margin: 10px 0; border-radius: 8px; }
          .value { font-size: 24px; font-weight: bold; color: #0891b2; }
          .label { color: #4b5563; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
          th { background: #f9fafb; }
          .footer { margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">🏭 Nexus Precision Industries</div>
          <div class="title">AI Manufacturing Intelligence Report</div>
          <div class="subtitle">Sample Report - Generated ${new Date().toLocaleDateString()}</div>
        </div>

        <div class="section">
          <h2>Production Efficiency Analysis</h2>
          <div style="display: flex; gap: 20px;">
            <div class="metric">
              <div class="value">94.3%</div>
              <div class="label">Overall Equipment Effectiveness (OEE)</div>
            </div>
            <div class="metric">
              <div class="value">87.2%</div>
              <div class="label">Machine Utilization</div>
            </div>
            <div class="metric">
              <div class="value">98.5%</div>
              <div class="label">Quality Rate</div>
            </div>
          </div>
        </div>

        <div class="section">
          <h2>Predictive Maintenance Insights</h2>
          <table>
            <tr>
              <th>Machine</th>
              <th>Risk Level</th>
              <th>Action Required</th>
              <th>Estimated Cost</th>
            </tr>
            <tr>
              <td>600 Ton Press</td>
              <td>High (85%)</td>
              <td>Maintenance in 3 days</td>
              <td>$12,000</td>
            </tr>
            <tr>
              <td>400 Ton Press</td>
              <td>Medium (65%)</td>
              <td>Maintenance in 7 days</td>
              <td>$8,000</td>
            </tr>
            <tr>
              <td>CNC Mill #3</td>
              <td>Low (45%)</td>
              <td>Monitor for 14 days</td>
              <td>$5,000</td>
            </tr>
          </table>
        </div>

        <div class="section">
          <h2>AI-Generated Recommendations</h2>
          <ul>
            <li><strong>Efficiency Optimization:</strong> Implement staggered shift changes to reduce downtime by 15 minutes per changeover</li>
            <li><strong>Quality Improvement:</strong> Part A-123 shows increasing defect rate - recommend die inspection within 48 hours</li>
            <li><strong>Cost Reduction:</strong> Consolidate maintenance windows to reduce labor costs by $23,000 annually</li>
            <li><strong>Predictive Alert:</strong> Machine #7 bearing temperature trending upward - schedule replacement before failure</li>
          </ul>
        </div>

        <div class="section">
          <h2>Time & Cost Savings Summary</h2>
          <div class="metric">
            <div class="value">$284,000</div>
            <div class="label">Annual waste reduction potential</div>
          </div>
          <div class="metric">
            <div class="value">127 hours</div>
            <div class="label">Prevented downtime this quarter</div>
          </div>
          <div class="metric">
            <div class="value">70%</div>
            <div class="label">Reduction in manual reporting time</div>
          </div>
        </div>

        <div class="footer">
          <p>This is a sample report generated by Nexus Manufacturing Intelligence Platform</p>
          <p>For a personalized demo with your actual ERP data, visit: https://aimpactnexus.ai/contact</p>
          <p>© 2025 Nexus Precision Industries - Beyond ERP, Manufacturing Intelligence</p>
        </div>
      </body>
      </html>
    `

    return new NextResponse(samplePdfContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="nexus-sample-report.html"'
      }
    })

  } catch (error) {
    console.error('PDF generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}